version: "3.4"

services:
  docker-mysql:
    container_name: docker-mysql
    restart: unless-stopped
    build:
      context: ./containers
      dockerfile: database.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=SPRING
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  race-management-service:
    container_name: racemanagement
    image: racemanagement
    depends_on:
      - docker-mysql
    build: 
      context: .
      target: dev
      dockerfile: containers/racemanagement.dockerfile
    restart: on-failure
    ports:
      - 8080:8080
      - 5015:5015
    volumes:
      - ./:/app
      - cache:/root/.gradle
    command: ./gradlew bootRun

volumes:
  db:
  cache:

networks:
  default:
    external:
      name: race-management
