version: "3.4"

services:
  docker-mysql:
    container_name: postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: containers/database.dockerfile
    environment:
      - MYSQL_DATABASE=SPRING
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/mysql

  race-management-service:
    container_name: racemanagement
    image: racemanagement
    depends_on:
      - docker-mysql
    build: 
      context: .
      target: dev
      dockerfile: containers/racemanagement.dockerfile
    ports:
      - 8080:8080
      - 5015:5015
    volumes:
      - ./:/app
      - cache:/root/.gradle
      - ~/race-management/logs/:/app/logs/
    command: ./gradlew bootRun -Dspring.profiles.active=local --no-daemon

volumes:
  db:
  cache:
  logging:

networks:
  default:
    external:
      name: race-management
