spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect:
          storage_engine: innodb
server:
  error:
    include-message: always