spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect:
          storage_engine: innodb
server:
  error:
    include-message: always
secret: ${SECRET_KEY}
users:
  test-user:
    username: ${TEST_USER}
    password: ${TEST_USER_PW}
  test-admin:
    username: ${TEST_ADMIN}
    password: ${TEST_ADMIN_PW}
