spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://docker-mysql:3306/${MYSQL_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: create
        dialect:
          storage_engine: innodb
    open-in-view: false
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    pretty-printing: true
logging:
  file:
    path: /logs
server:
  error:
    include-message: always
secret: ${SECRET_KEY}
users:
  test-user:
    username: ${TEST_USER}
    password: ${TEST_USER_PW}
    id: ${TEST_USER_ID}
  test-admin:
    username: ${TEST_ADMIN}
    password: ${TEST_ADMIN_PW}
    id: ${TEST_ADMIN_ID}
