spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    # url: jdbc:mysql://docker-mysql:3306/${MYSQL_DATABASE}
    url: jdbc:postgresql://postgres:5432/spring
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        hbm2ddl:
          auto: update
logging:
  file:
    path: /logs/
server:
  error:
    include-message: always
secret: ${SECRET_KEY}
users:
  test-user:
    username: ${TEST_USER}
    password: ${TEST_USER_PW}
    id: ${TEST_USER_ID}
  test-admin:
    username: ${TEST_ADMIN}
    password: ${TEST_ADMIN_PW}
    id: ${TEST_ADMIN_ID}
