# .circleci/config.yml
version: 2.1
jobs:
  build-application:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Gradle Build
          command: ./gradlew build -x test
      - store_artifacts:
          path: build/libs/*.jar
          name: app.jar
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Test Application
          command: ./gradlew test -i
      - run:
          name: Consolidate test results
          command: cp build/reports/jacoco/all-tests/jacocoAllTests.xml build/test-results/test/jacocoAllTests.xml
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/jacoco/html
      - run:
          name: Upload Test Results
          command: bash <(curl -s https://codecov.io/bash)
  integration-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Integration Tests
          command: ./gradlew integrationTest

workflows:
  build:
    jobs:
      - build-application
      - test
      - integration-test:
          requires:
            - build-application
            - test
# Uncomment this when we validate that the automation runs in the pipeline ok
#          filters:
#            branches:
#              only:
#                - main
