# .circleci/config.yml
version: 2.1
jobs:
  build-application:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Gradle Build
          command: ./gradlew build -x test
      # Cache build deps until build.gradle changes
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
          paths:
            - ~/.gradle/caches/modules-2/files-2.1
      - store_artifacts:
          path: build/libs/*.jar
          name: app.jar
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Test Application
          command: ./gradlew test -i
      - run:
          name: Consolidate Test Results
          command: cp build/reports/jacoco/all-tests/jacocoAllTests.xml build/test-results/test/jacocoAllTests.xml
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/jacoco/html
      - run:
          name: Upload Test Results
          command: bash <(curl -s https://codecov.io/bash)
  integration-test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties }}
      - run:
          name: Start Docker Daemon
          command: sudo systemctl start docker
      - run:
          name: Java Version Check
          command: java --version
      - run:
          name: Run Integration Tests
          command: ./gradlew integrationTest
      - store_test_results:
          path: build/test-results/integrationTest
  store-built-application:
      docker:
        - image: cimg/openjdk:17.0
      steps:
        - checkout
        - restore_cache:
            keys:
              - cache-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
        - run:
            name: Build Application
            command: ./gradlew jar
        - store_artifacts:
            path: build/libs/*.jar
            name: app.jar

workflows:
  build:
    jobs:
      - build-application
      - test
      - integration-test:
          requires:
            - build-application
          filters:
            branches:
              only:
                - main
      - store-built-application:
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - main
