# .circleci/config.yml
version: 2.1
jobs:
  build-application:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Gradle Build
          command: ./gradlew build -x test
      - store_artifacts:
          path: build/libs/*.jar
          name: app.jar
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Test Application
          command: ./gradlew test -i
      - store_test_results:
          path: build/reports/jacoco/all-tests/*.xml
      - store_artifacts:
          path: build/reports/jacoco/all-tests/html
      - run:
          name: Upload Test Results
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  build:
    jobs:
      - build-application
      - test
