spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: tester
    password: password # pragma: allowlist secret
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.20:///test?TC_INITSCRIPT=file:src/integrationTest/resources/init.sql
  jpa:
    properties:
      hibernate:
        ddl-auto: create
logging:
  group:
    testImpl: com.teddycrane.racemanagement.test.integration.tests
  level:
    testImpl: info
server:
  error:
    include-message: always
secret: ${SECRET_KEY}
users:
  test-user:
    username: ${TEST_USER}
    password: ${TEST_USER_PW}
    id: ${TEST_ADMIN_ID}
  test-admin:
    username: ${TEST_ADMIN}
    password: ${TEST_ADMIN_PW}
    id: ${TEST_ADMIN_ID}
